// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Ship":return img`
................................
................................
................................
................................
................................
................................
.............222222.............
............22222222............
...........222f22f222...........
..........2222f22f2222..........
..........2222f22f2222..........
.........22822f22f22822.........
.....888.22822f22f22822.888.....
....8555822822f22f2282285558....
....8555822822f22f2282285558....
...85555582822f22f22828555558...
...88558582822f22f22828585588...
...88558582822f22f22828585588...
...88558582822222222828585588...
...88558582822222222828585588...
...88558582822f22f22828585588...
...88558582822222222828585588...
...88558582822f22f22828585588...
...88558582822222222828585588...
...85555582822f22f22828555558...
....855582282222222282285558....
....8555822822f22f2282285558....
.....888222822f22f228222888.....
.........22822222222822.........
..........222222222222..........
................................
................................
`;
            case "image2":
            case "sky1":return img`
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffcffffffffffcfffffffffffffffffffffffffffffcffffffffffcfffffffffffffffffffffffffffffcfffffffffffcffffffffffffffffffffffffffffccffffffffffcffffffffffffffffff
ffffffffffffffffcbcfffffffffffffffffffffcffffffffffffffffcbcfffffffffffffffffffffcfffffffffffffffffcbcffffffffffffffffffffcfffffffffffffffffcbcfffffffffffffffff
fffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffccffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcfff
ffffffffffffffffffffffffffffffffccffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcfff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffff
fffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffcbcffffffff
fff3fffffffffffffffffffffbbbffffffffffffffff3ffffffffffffffffffffffbbbfffffffffffffff3ffffffffffffffffffffffbbbfffffffffffffff3ffffffffffffffffffffffbbbffffffff
ffb3bffffffffffffffffffffcbcfffffffffffffffb3bfffffffffffffffffffffcbcffffffffffffffb3bfffffffffffffffffffffcbcffffffffffffffb3bfffffffffffffffffffffcbcffffffff
333333ffffffffffffccffffffffffffffffffffff33333ffffffffffffccffffffffffffffffffffff33333fffffffffffffccfffffffffffffffffffff33333fffffffffffffccffffffffffffffff
ff3b3fffffffffffffccfffffffffffffffffffffff3b3fffffffffffffccfffffffffffffffffffffff3b3ffffffffffffffccffffffffffffffffffffff3b3ffffffffffffffccffffffffffffffff
ffbfbffffffffffffffffffffffffffffffcfffffffbfbffffffffffffffffffffffffffffffcfffffffbfbffffffffffffffffffffffffffffffcfffffffbfbffffffffffffffffffffffffffffffcf
ffbfbffffffffffffffffffffffffffffffcfffffffbfbffffffffffffffffffffffffffffffcfffffffbfbffffffffffffffffffffffffffffffcfffffffbfbffffffffffffffffffffffffffffffcf
ffffffffffffffffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffcbc
fffffffffffcfffffffffffffffffffffffcffffffffffffffffcfffffffffffffffffffffffcffffffffffffffffcfffffffffffffffffffffffcfffffffffffffffffcffffffffffffffffffffffcf
ffffffffffcbcffffffffffffffffffffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffff
fffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ccfffffffffffffffffffffffffcffffffffffffffcffffffffffffffffffffffffffcfffffffffffffcffffffffffffffffffffffffffcfffffffffffffcffffffffffffffffffffffffffcffffffff
fffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffff
fffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffff
fffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcf
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffccfffffcfffffffffffffffffffffffffffffffffccfffffcfffffffffffffffffffffffffffffffffccfffffcfffffffffffffffffffffffffffffffffcccfffffcffffffffffffffffffffff
ffffffccfffffffffffffffffffffffffffffffffffffffccfffffffffffffffffffffffffffffffffffffffccfffffffffffffffffffffffffffffffffffffffcccffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffccfffffcfffffffffffffffffffffffffffffffffccfffffcfffffffffffffffffffffffffffffffffccfffffcfffffffffffffffffffffffffffffffffcccfffffcfffffffffffffffffffffff
fffffccfffffffffffffffffffffffffffffffffffffffccfffffffffffffffffffffffffffffffffffffffccfffffffffffffffffffffffffffffffffffffffcccfffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
cfffffffffffffffffffffffffffffcffffffffffcfffffffffffffffffffffffffffffcfffffffffffcffffffffffffffffffffffffffffccffffffffffcfffffffffffffffffffffffffffffffffff
bcfffffffffffffffffffffcffffffffffffffffcbcfffffffffffffffffffffcfffffffffffffffffcbcffffffffffffffffffffcfffffffffffffffffcbcffffffffffffffffffffffffffffffffff
cffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffccffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffff
fffffffffffffffccffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffff
ffffffffcbcfffffffffffffffffffffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffff
ffffffffbbbffffffffffffffff3ffffffffffffffffffffffbbbfffffffffffffff3ffffffffffffffffffffffbbbfffffffffffffff3ffffffffffffffffffffffbbbfffffffffffffffffffffffff
ffffffffcbcfffffffffffffffb3bfffffffffffffffffffffcbcffffffffffffffb3bfffffffffffffffffffffcbcffffffffffffffb3bfffffffffffffffffffffcbcfffffffffffffffffffffffff
fccffffffffffffffffffffff33333ffffffffffffccffffffffffffffffffffff33333fffffffffffffccfffffffffffffffffffff33333fffffffffffffccfffffffffffffffffffffffffffffffff
fccfffffffffffffffffffffff3b3fffffffffffffccfffffffffffffffffffffff3b3ffffffffffffffccffffffffffffffffffffff3b3ffffffffffffffccfffffffffffffffffffffffffffffffff
ffffffffffffffffffcfffffffbfbffffffffffffffffffffffffffffffcfffffffbfbffffffffffffffffffffffffffffffcfffffffbfbffffffffffffffffffffffffffffffcffffffffffffffffff
ffffffffffffffffffcfffffffbfbffffffffffffffffffffffffffffffcfffffffbfbffffffffffffffffffffffffffffffcfffffffbfbffffffffffffffffffffffffffffffcffffffffffffffffff
fffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffcbcfffffffffffffffff
ffffffffffffffffffcffffffffffffffffcfffffffffffffffffffffffcffffffffffffffffcfffffffffffffffffffffffcfffffffffffffffffcffffffffffffffffffffffcffffffffffffffffff
ffffffffffffffffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffcffffffffffffffcffffffffffffffffffffffffffcfffffffffffffcffffffffffffffffffffffffffcfffffffffffffcffffffffffffffffffffffffffcfffffffffffffffffffffffff
cffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffff
cffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffff
ffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffccfffffcfffffffffffffffffffffffffffffffffccfffffcfffffffffffffffffffffffffffffffffcccfffffcfffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffccfffffffffffffffffffffffffffffffffffffffccfffffffffffffffffffffffffffffffffffffffcccfffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffcffffffffffcfffffffffffffffffffffffffffffcffffffffffcfffffffffffffffffffffffffffffcfffffffffffcffffffffffffffffffffffffffffccfffff
ffffffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffcffffffffffffffffcbcfffffffffffffffffffffcfffffffffffffffffcbcffffffffffffffffffffcfffffffffffff
fffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffccffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffccffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffff
fffffffffffffffffffffffffff3fffffffffffffffffffffbbbffffffffffffffff3ffffffffffffffffffffffbbbfffffffffffffff3ffffffffffffffffffffffbbbfffffffffffffff3fffffffff
ffffffffffffffffffffffffffb3bffffffffffffffffffffcbcfffffffffffffffb3bfffffffffffffffffffffcbcffffffffffffffb3bfffffffffffffffffffffcbcffffffffffffffb3bffffffff
ffffffffffffffffffffffff333333ffffffffffffccffffffffffffffffffffff33333ffffffffffffccffffffffffffffffffffff33333fffffffffffffccfffffffffffffffffffff33333fffffff
ffffffffffffffffffffffffff3b3fffffffffffffccfffffffffffffffffffffff3b3fffffffffffffccfffffffffffffffffffffff3b3ffffffffffffffccffffffffffffffffffffff3b3ffffffff
ffffffffffffffffffffffffffbfbffffffffffffffffffffffffffffffcfffffffbfbffffffffffffffffffffffffffffffcfffffffbfbffffffffffffffffffffffffffffffcfffffffbfbffffffff
ffffffffffffffffffffffffffbfbffffffffffffffffffffffffffffffcfffffffbfbffffffffffffffffffffffffffffffcfffffffbfbffffffffffffffffffffffffffffffcfffffffbfbffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffcbcfffffffffffffffff
fffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffcffffffffffffffffcfffffffffffffffffffffffcffffffffffffffffcfffffffffffffffffffffffcfffffffffffffffffc
ffffffffffffffffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffcbcfffffffffffffffffffffffffffffffffffffffcb
fffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffc
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffccfffffffffffffffffffffffffcffffffffffffffcffffffffffffffffffffffffffcfffffffffffffcffffffffffffffffffffffffffcfffffffffffffcfffffffffff
fffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffcffffffffffcfffffffffffffffffffffffffffffcfffffffffffcffffffffffffffffffffffffffffccffffffffffcfffffffffffffffffffffffffffffffffffffffcccffff
ffffffffffffcffffffffffffffffcbcfffffffffffffffffffffcfffffffffffffffffcbcffffffffffffffffffffcfffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffcccffff
ffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffccffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffff
ffffccffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffff
ffffffffffffffff3ffffffffffffffffffffffbbbfffffffffffffff3ffffffffffffffffffffffbbbfffffffffffffff3ffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffff
fffffffffffffffb3bfffffffffffffffffffffcbcffffffffffffffb3bfffffffffffffffffffffcbcffffffffffffffb3bfffffffffffffffffffffcbcffffffffffffffffffffffffffffffffffff
ffffffffffffff33333ffffffffffffccffffffffffffffffffffff33333fffffffffffffccfffffffffffffffffffff33333fffffffffffffccffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff3b3fffffffffffffccfffffffffffffffffffffff3b3ffffffffffffffccffffffffffffffffffffff3b3ffffffffffffffccffffffffffffffffffffffffffffffffffffffffffff
fffffffcfffffffbfbffffffffffffffffffffffffffffffcfffffffbfbffffffffffffffffffffffffffffffcfffffffbfbffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffff
fffffffcfffffffbfbffffffffffffffffffffffffffffffcfffffffbfbffffffffffffffffffffffffffffffcfffffffbfbffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffff
`;
            case "image3":
            case "target":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
